# Generated by Django 5.0.14 on 2026-05-10 09:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity_date', models.DateField()),
            ],
            options={
                'ordering': ['activity_date', 'city_stop__order'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('miscellaneous_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CityStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('toiletries', 'Toiletries'), ('medicine', 'Medicine'), ('other', 'Other')], default='other', max_length=30)),
                ('is_packed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='trip_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_travel_style',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='city_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel.citystop'),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='note',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='citystop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_stops', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='budget',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='travel.trip'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AlterUniqueTogether(
            name='citystop',
            unique_together={('trip', 'order')},
        ),
    ]
