# Generated by Django 5.0.14 on 2026-05-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_activity_budget_citystop_note_packingitem_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveSmallIntegerField(default=5)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_travelers', models.PositiveSmallIntegerField(default=8)),
                ('image_url', models.URLField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.destination')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'ordering': ['destination', 'name'],
            },
        ),
    ]
